
[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gotest.tools"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-tty"
