FROM    golang:1.8-alpine

RUN     apk add -U curl git bash
RUN     export GLIDE=v0.12.3; \
        export SRC=https://github.com/Masterminds/glide/releases/download/; \
        curl -sL ${SRC}/${GLIDE}/glide-${GLIDE}-linux-amd64.tar.gz | \
        tar -xz linux-amd64/glide && \
        mv linux-amd64/glide /usr/bin/glide && \
        chmod +x /usr/bin/glide

WORKDIR /go/src/github.com/dnephin/filewatcher
ENV     CGO_ENABLED=0
